### ISSUE TITLE
[BUG] Parse Error: Syntax error, unexpected T_MATCH

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [phparkitect/arkitect#108]
When you invoke a class named `Match` PhpParser throw an error:

```
Parse Error: Syntax error, unexpected T_MATCH on line 10#0 /arkitect/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(158): PhpParser\ParserAbstract->doParse()
#1 /arkitect/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse('<?php\ndeclare(s...', Object(PhpParser\ErrorHandler\Throwing))
#2 /arkitect/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php\ndeclare(s...')
...
```

The problem is the name `Match` because in PHP8 is a reserved key.
We need to specify that we are using PHP7.1 for example.

**Comment by AlessandroMinoccheri** [comment]
Closed by #109
