### ISSUE TITLE
Array shape docblocks causing issues since 0.3.3

### ISSUE THREAD

**Issue by ostrolucky** [phparkitect/arkitect#311]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        |no
| Library Version | 0.3.3
| PHP version     | 8.1.11

#### Summary

After updating phparkitect, output is ridden with these kind of errors
```
Parse Error: Haushalt\Bl\DomainBundle\Application\ItemData\Helper\array<int, Product> is not a valid namespace definition#0 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/Analyzer/ClassDependency.php(17): Arkitect\Analyzer\FullyQualifiedClassName::fromString()
#1 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/Analyzer/FileVisitor.php(156): Arkitect\Analyzer\ClassDependency->__construct()
#2 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Arkitect\Analyzer\FileVisitor->enterNode()
#3 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#4 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#5 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#6 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#7 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#8 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/Analyzer/FileParser.php(74): PhpParser\NodeTraverser->traverse()
#9 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/CLI/Runner.php(57): Arkitect\Analyzer\FileParser->parse()
#10 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/CLI/Runner.php(40): Arkitect\CLI\Runner->check()
#11 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/CLI/Command/Check.php(92): Arkitect\CLI\Runner->run()
#12 /vagrant/fe-bl-domain/vendor/symfony/console/Command/Command.php(308): Arkitect\CLI\Command\Check->execute()
#13 /vagrant/fe-bl-domain/vendor/symfony/console/Application.php(1014): Symfony\Component\Console\Command\Command->run()
#14 /vagrant/fe-bl-domain/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#15 /vagrant/fe-bl-domain/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#16 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/bin-stub/phparkitect(32): Symfony\Component\Console\Application->run()
#17 /vagrant/fe-bl-domain/vendor/bin/phparkitect(120): include('...')
#18 {main}Parse Error: Haushalt\Bl\DomainBundle\Application\ItemData\Helper\array<int, OfferList> is not a valid namespace definition#0 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/Analyzer/ClassDependency.php(17): Arkitect\Analyzer\FullyQualifiedClassName::fromString()
#1 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/Analyzer/FileVisitor.php(156): Arkitect\Analyzer\ClassDependency->__construct()
#2 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Arkitect\Analyzer\FileVisitor->enterNode()
#3 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#4 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#5 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#6 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#7 /vagrant/fe-bl-domain/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#8 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/Analyzer/FileParser.php(74): PhpParser\NodeTraverser->traverse()
#9 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/CLI/Runner.php(57): Arkitect\Analyzer\FileParser->parse()
#10 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/CLI/Runner.php(40): Arkitect\CLI\Runner->check()
#11 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/src/CLI/Command/Check.php(92): Arkitect\CLI\Runner->run()
#12 /vagrant/fe-bl-domain/vendor/symfony/console/Command/Command.php(308): Arkitect\CLI\Command\Check->execute()
#13 /vagrant/fe-bl-domain/vendor/symfony/console/Application.php(1014): Symfony\Component\Console\Command\Command->run()
#14 /vagrant/fe-bl-domain/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#15 /vagrant/fe-bl-domain/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#16 /vagrant/fe-bl-domain/vendor/phparkitect/phparkitect/bin-stub/phparkitect(32): Symfony\Component\Console\Application->run()
#17 /vagrant/fe-bl-domain/vendor/bin/phparkitect(120): include('...')
```

**Comment by AlessandroMinoccheri** [comment]
Hi @ostrolucky can you please share the docblock that generates the error ?

**Comment by ostrolucky** [comment]
```php
class Foos
{
    /** @var array<int, \stdClass> */
    private array $foos = [];
}
```

**Comment by AlessandroMinoccheri** [comment]
@ostrolucky we released the new version with the fix for your problem, can you please try and give us feedback?
We are sorry for the inconvenience.

**Comment by ostrolucky** [comment]
Works now 👍 thx
